package com.trustlayer.shared.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    MALFORMED_REQUEST(HttpStatus.BAD_REQUEST),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    ACCOUNT_LOCKED(HttpStatus.LOCKED),
    INVALID_TOKEN(HttpStatus.BAD_REQUEST),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    EMAIL_ALREADY_REGISTERED(HttpStatus.CONFLICT),
    WEAK_PASSWORD(HttpStatus.BAD_REQUEST),
    EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN),
    IDENTITY_NOT_VERIFIED(HttpStatus.FORBIDDEN),
    IDENTITY_ALREADY_VERIFIED(HttpStatus.CONFLICT),
    VERIFICATION_IN_PROGRESS(HttpStatus.CONFLICT),
    VERIFICATION_ATTEMPTS_EXHAUSTED(HttpStatus.CONFLICT),
    VERIFICATION_SESSION_EXPIRED(HttpStatus.CONFLICT),
    INVALID_WEBHOOK_SIGNATURE(HttpStatus.BAD_REQUEST),
    PROVIDER_ERROR(HttpStatus.BAD_GATEWAY),
    PROVIDER_NOT_CONFIGURED(HttpStatus.SERVICE_UNAVAILABLE),
    IDEMPOTENCY_KEY_REQUIRED(HttpStatus.BAD_REQUEST),
    IDEMPOTENCY_KEY_REUSED(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUEST_IN_PROGRESS(HttpStatus.CONFLICT),
    ALREADY_SUBSCRIBED(HttpStatus.CONFLICT),
    PLAN_NOT_FOUND(HttpStatus.NOT_FOUND),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
