package com.trustlayer.shared.event;

public enum EventType {
    USER_REGISTERED,
    EMAIL_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    IDENTITY_VERIFIED,
    IDENTITY_REJECTED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELLED,
    ACCESS_GRANTED,
    ACCESS_BLOCKED
}
